image:
    tag: ENC[AES256_GCM,data:vwhGWw==,iv:s3PmY8JMw9F49Rw47UbZu34V8OTk5MEqP24bSPPgGl0=,tag:vHYIzXXXmyUNAVUkbGNIGQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/playground-226302/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2019-03-01T11:36:21Z'
        enc: CiQA9CJCaheiMw+JeRiMvKar+26ti+zuYpcc6hEqehBfEkDTX4YSSQBb2sFTDBULXkFbh4N0h+QbPR4nwlaRqeUKf7LsM3kxvFIfM4Nh6JQfL7XbGuEU1Px/wvdn9L14S8IMvxXSua/Q6GeP4Pijfqo=
    azure_kv: []
    lastmodified: '2019-03-01T11:36:30Z'
    mac: ENC[AES256_GCM,data:LHNaTB8lymx7himRROuBrajkWonIi4o9yeUjKT2KXidPArR3nWMrgJOe+GOni/OtfG4wizWwqO5asRPEhX8+3diPk4Xyt7ZdzuBTSmmsTxreoAWURVMHakH0jmOJj44VsLO5KVA6DincUqiKjiwbsVLV0CZMUcbTkpDPoAyDqZ4=,iv:cnk9yaOUYL6l7pRMMkIdxlbQBJXScPwzr2aOg+NgjbI=,tag:TWK5/as7l89TXX+f0pZspA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.1.0
